name: Android Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Retrieve the secret and decode it to a file
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
          DEBUG_KEYSTORE_BASE64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}

        run: |
          echo $GOOGLE_SERVICES_JSON_BASE64 | base64 -di > app/google-services.json
          echo DEBUG_KEYSTORE_BASE64 | base64 -di > app/debug.keystore

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests with Gradle
        run: ./gradlew test